name: Echo service

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test branch
        run: |
          echo ${{ secrets.SEEKRIT_PASSWORD }} | tr a-z n-za-m
          echo ${{ secrets.SEEKRIT_PASSWORD }}+1
