name: Echo service

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ secrets.SEEKRIT_PASSWORD }} == 'hunter2'
    steps:
      - name: Test branch
        run: |
          echo "you are hacked"
